/**
 * generators/catalog.mjs — emits a standalone `catalog.js` for filter-mode
 * stores (config.catalog.mode === 'filter'), mirroring the existing
 * src/stores/fcm/catalog.js / src/stores/pvz3/catalog.js convention: keeping
 * the category tree + featured items in their own file (not inlined into
 * store.js) is what the repo already does for this catalogue model, so a
 * generated store matches the pattern a hand-written one would follow.
 *
 * Uses the same asset-path-as-import convention as store-module.mjs — see
 * that file's header for why (every image must stay a build-time Vite import).
 */

// Reuse store-module.mjs's private marking/serialization by re-implementing
// the small shared bit inline — kept intentionally tiny and dependency-free
// rather than exporting internals across generator files for a two-function
// need.
const ASSET_PATH_RE = /^(\.\.?\/|@\/)/
class AssetRef { constructor (path) { this.path = path } }
function markAssets (value) {
  if (typeof value === 'string' && ASSET_PATH_RE.test(value)) return new AssetRef(value)
  if (Array.isArray(value)) return value.map(markAssets)
  if (value && typeof value === 'object') {
    const out = {}
    for (const [k, v] of Object.entries(value)) out[k] = markAssets(v)
    return out
  }
  return value
}
function collectAssetPaths (value, seen = new Set(), order = []) {
  if (value instanceof AssetRef) { if (!seen.has(value.path)) { seen.add(value.path); order.push(value.path) }; return order }
  if (Array.isArray(value)) { for (const v of value) collectAssetPaths(v, seen, order); return order }
  if (value && typeof value === 'object') { for (const v of Object.values(value)) collectAssetPaths(v, seen, order); return order }
  return order
}
function identFor (assetPath, used) {
  const stem = assetPath.split('/').pop().replace(/\.[a-z0-9]+$/i, '')
  let ident = stem.replace(/[^a-zA-Z0-9]+(.)/g, (_, c) => c.toUpperCase()).replace(/[^a-zA-Z0-9]/g, '').replace(/^[0-9]/, '_$&')
  if (!ident) ident = 'asset'
  ident = ident[0].toLowerCase() + ident.slice(1)
  let candidate = ident, n = 1
  while (used.has(candidate)) candidate = `${ident}${n++}`
  used.add(candidate)
  return candidate
}
function jsKey (key) { return /^[a-zA-Z_$][a-zA-Z0-9_$]*$/.test(key) ? key : JSON.stringify(key) }
function toJs (value, identMap, indent = 0) {
  const pad = '  '.repeat(indent), padIn = '  '.repeat(indent + 1)
  if (value instanceof AssetRef) return identMap.get(value.path)
  if (value === null || value === undefined) return 'null'
  if (typeof value === 'number' || typeof value === 'boolean') return String(value)
  if (typeof value === 'string') return JSON.stringify(value)
  if (Array.isArray(value)) {
    if (!value.length) return '[]'
    return `[\n${value.map(v => `${padIn}${toJs(v, identMap, indent + 1)}`).join(',\n')}\n${pad}]`
  }
  const entries = Object.entries(value)
  if (!entries.length) return '{}'
  return `{\n${entries.map(([k, v]) => `${padIn}${jsKey(k)}: ${toJs(v, identMap, indent + 1)}`).join(',\n')}\n${pad}}`
}

/**
 * @param {object} def
 * @param {string} def.label
 * @param {Array} def.catalog - [{ id, label, subcategories: [{ id, label, cardType, items[] }] }]
 * @param {Array|null} [def.featured]
 */
export function generateCatalogModule (def) {
  const { label, catalog, featured = null } = def
  if (!catalog) throw new Error('def.catalog is required for a filter-mode store')

  const marked = markAssets({ catalog, featured })
  const assetPaths = collectAssetPaths(marked)
  const used = new Set()
  const identMap = new Map()
  for (const path of assetPaths) identMap.set(path, identFor(path, used))

  const importLines = assetPaths.map(p => `import ${identMap.get(p)} from ${JSON.stringify(p)}`).join('\n')

  return `/**
 * ${label} — SKU catalogue tree + featured items. GENERATED by tools/cms
 * (catalog.mjs). Edit the store's store.config.json (or the CMS dashboard)
 * and regenerate — do not hand-edit this file directly.
 *
 * Structure: [ { id, label, subcategories: [ { id, label, cardType, items[] } ] } ]
 * cardType 'bundle' → BundleSkuCard props; 'sku' → SkuImageCard props;
 * 'hero' → HeroSkuCard props. See tools/cms/schema/cards.js.
 */

${importLines}

export const catalog = ${toJs(marked.catalog, identMap, 0)}

export const featured = ${toJs(marked.featured, identMap, 0)}
`
}
