#!/usr/bin/env node
/**
 * tools/sandbox/generate-ruleset.mjs — regenerates the sandbox's ruleset
 * docs from the real skill files, per tools/sandbox/ruleset.manifest.mjs.
 *
 * A maintainer action, NOT run at every bundle export — the ruleset is the
 * same across exports unless a skill's wording changed. Run this whenever
 * ruleset.manifest.mjs changes, or a referenced skill file is reworded.
 *
 * Usage:
 *   node tools/sandbox/generate-ruleset.mjs           # write the docs
 *   node tools/sandbox/generate-ruleset.mjs --check   # dry-run drift check,
 *                                                      # exit 1 if stale
 *
 * See /Users/yiwei/.claude/plans/majestic-noodling-teapot.md (Milestone 2 §3).
 */
import { existsSync, readFileSync, writeFileSync } from 'node:fs'
import path from 'node:path'
import { fileURLToPath } from 'node:url'
import { section, truncateBeforeHeading } from './lib/markdown.mjs'
import { RULESET_DOCS, AGENTS_HARD_RULES, SKILL_PATHS } from './ruleset.manifest.mjs'

const __dirname = path.dirname(fileURLToPath(import.meta.url))
const TEMPLATE_DIR = path.join(__dirname, 'template')
const AGENTS_PATH = path.join(TEMPLATE_DIR, 'AGENTS.md')

const isCheck = process.argv.includes('--check')

const BANNER =
  '<!-- GENERATED by tools/sandbox/generate-ruleset.mjs — do not hand-edit.\n' +
  '     Edit tools/sandbox/ruleset.manifest.mjs instead, then re-run\n' +
  '     `npm run sandbox:ruleset` at the repo root. -->\n\n'

/** Extracts one manifest section entry's body, applying its `filter` if any. */
function extractSection(entry) {
  const skillPath = SKILL_PATHS[entry.skill]
  if (!skillPath || !existsSync(skillPath)) {
    console.error(`✗ Skill file not found for "${entry.skill}": ${skillPath}`)
    console.error('  (referenced by tools/sandbox/ruleset.manifest.mjs)')
    process.exit(1)
  }
  const content = readFileSync(skillPath, 'utf8')
  let body = section(content, entry.heading)
  if (!body) {
    console.error(`✗ Heading "## ${entry.heading}" not found in ${skillPath}.`)
    console.error('  The skill may have been reworded — update ruleset.manifest.mjs to match.')
    process.exit(1)
  }
  if (entry.stopBefore) {
    const truncated = truncateBeforeHeading(body, entry.stopBefore)
    if (truncated === body) {
      console.error(`✗ stopBefore heading "${entry.stopBefore}" not found inside "## ${entry.heading}" in ${skillPath}.`)
      console.error('  The skill may have been reworded — update ruleset.manifest.mjs to match.')
      process.exit(1)
    }
    body = truncated
  }
  if (entry.filter) {
    body = body.split('\n').filter((line) => line.trim() === '' || entry.filter(line)).join('\n').trim()
    if (!body) {
      console.error(`✗ Filter for "${entry.skill}" § "${entry.heading}" matched nothing — ` +
        'the checklist may have been reworded; update the filter in ruleset.manifest.mjs.')
      process.exit(1)
    }
  }
  return body
}

function renderRulesetDoc(spec) {
  const sections = spec.sections.map((entry) =>
    `### Source: \`${entry.skill}\` — "${entry.heading}"\n\n${extractSection(entry)}\n`,
  ).join('\n')
  return `${BANNER}${spec.intro.trim()}\n\n${sections}`
}

function renderHardRules() {
  return AGENTS_HARD_RULES.sections.map((entry) =>
    `${BANNER}${extractSection(entry)}\n`,
  ).join('\n')
}

const MARKER_BEGIN = '<!-- GENERATED:HARD_RULES:BEGIN'
const MARKER_END = '<!-- GENERATED:HARD_RULES:END -->'

function spliceAgentsMd(currentContent, newBlock) {
  const beginIdx = currentContent.indexOf(MARKER_BEGIN)
  const endIdx = currentContent.indexOf(MARKER_END)
  if (beginIdx === -1 || endIdx === -1) {
    console.error(`✗ AGENTS.md is missing its GENERATED:HARD_RULES markers — cannot splice.`)
    process.exit(1)
  }
  const beginLineEnd = currentContent.indexOf('\n', beginIdx) + 1
  return currentContent.slice(0, beginLineEnd) + newBlock + currentContent.slice(endIdx)
}

let anyStale = false

function writeOrCheck(relPath, rendered) {
  const outPath = path.join(TEMPLATE_DIR, relPath)
  const current = existsSync(outPath) ? readFileSync(outPath, 'utf8') : null
  if (isCheck) {
    if (current !== rendered) {
      console.error(`✗ Stale: ${relPath} does not match its manifest-derived content.`)
      anyStale = true
    } else {
      console.log(`  ✓ ${relPath} in sync`)
    }
  } else {
    writeFileSync(outPath, rendered, 'utf8')
    console.log(`  wrote ${relPath}`)
  }
}

// ─── ruleset/*.md — fully generated ────────────────────────────────────────
for (const [relPath, spec] of Object.entries(RULESET_DOCS)) {
  writeOrCheck(relPath, renderRulesetDoc(spec))
}

// ─── AGENTS.md — one spliced block ─────────────────────────────────────────
const agentsCurrent = readFileSync(AGENTS_PATH, 'utf8')
const hardRulesBlock = renderHardRules()
const agentsRendered = spliceAgentsMd(agentsCurrent, hardRulesBlock)
if (isCheck) {
  const currentBlock = agentsCurrent.slice(
    agentsCurrent.indexOf('\n', agentsCurrent.indexOf(MARKER_BEGIN)) + 1,
    agentsCurrent.indexOf(MARKER_END),
  )
  if (currentBlock !== hardRulesBlock) {
    console.error(`✗ Stale: AGENTS.md's GENERATED:HARD_RULES block does not match its manifest-derived content.`)
    anyStale = true
  } else {
    console.log(`  ✓ AGENTS.md in sync`)
  }
} else {
  writeFileSync(AGENTS_PATH, agentsRendered, 'utf8')
  console.log(`  wrote AGENTS.md (HARD_RULES block)`)
}

if (isCheck) {
  if (anyStale) {
    console.error('\n✗ Ruleset docs are stale. Run `npm run sandbox:ruleset` to regenerate.')
    process.exit(1)
  }
  console.log('\n✓ Ruleset docs are in sync with their source skill files.')
} else {
  console.log('\n✓ Ruleset regenerated from source skills.')
}
